
import Foundation
import AccountsJourney

// swiftlint:disable line_length
final public class MockedAccountsUseCase: AccountsListUseCase {
    private var responseType: Result<Void, Error>
    
    /// Initialize an instance of MockedAccountsUseCase
    /// - Parameter responseType: Result type
    public init(responseType: Result<Void, Error>) {
        self.responseType = responseType
    }
    
    /// Gets a listing of accounts
    /// - Parameter completion: a result type object with either the accounts or error.
    public func getAccountSummary(_ completion: @escaping (Result<AccountsJourney.AccountsSummary, AccountsJourney.ErrorResponse>) -> Void) {
        switch responseType {
        case .failure(let error):
            completion(.failure(.init(error: error)))
        case .success:
            completion(.success(.init(customProducts: [], aggregatedBalance: .none, currentAccounts: .init(products: [
                .init(bookedBalance: "0.4200000000", availableBalance: "0.4200000000", creditLimit: "0.00000", iban: .none, bban: "***************6944", currency: "USD", urgentTransferAllowed: .none, bic: "USXBUSHQXXX", bankBranchCode: "123123123", bankBranchCode2: .none, accountInterestRate: 3.00, valueDateBalance: .none, creditLimitUsage: 0.00000, creditLimitInterestRate: 2.00, creditLimitExpiryDate: .none, accruedInterest: .none, debitCardsItems: [], accountHolderNames: "Sara Williams Williams", startDate: .none, minimumRequiredBalance: .none, accountHolderAddressLine1: .none, accountHolderAddressLine2: .none, accountHolderStreetName: .none, town: .none, postCode: .none, countrySubDivision: .none, creditAccount: .none, debitAccount: .none, accountHolderCountry: .none, additions: .none, identifier: .none, unmaskableAttributes: [.bban], name: "Retirement Account", displayName: "Ivet Ivanova", externalTransferAllowed: true, crossCurrencyAllowed: true, productKindName: "Current Account", productTypeName: "Current Account", bankAlias: "Retirement Account", sourceId: .none, visible: true, accountOpeningDate: .now, lastUpdateDate: .now, userPreferences: .init(alias: "Ivet Ivanova", visible: false, favorite: true, additions: nil), state: .init(externalStateId: "Active", state: "Active", additions: .none), parentId: .none, subArrangements: .none, financialInstitutionId: .none, lastSyncDate: .none, nextClosingDate: .none, reservedAmount: .none, remainingPeriodicTransfers: .none, overdueSince: .none, externalAccountStatus: .none, cardDetails: .none, interestDetails: .none),
                .init(bookedBalance: "0.4200000000", availableBalance: "0.4200000000", creditLimit: "0.00000", iban: .none, bban: "***************6945", currency: "USD", urgentTransferAllowed: .none, bic: "USXBUSHQXXX", bankBranchCode: "123123123", bankBranchCode2: .none, accountInterestRate: 3.00, valueDateBalance: .none, creditLimitUsage: 0.00000, creditLimitInterestRate: 2.00, creditLimitExpiryDate: .none, accruedInterest: .none, debitCardsItems: [], accountHolderNames: "Sarah William", startDate: .none, minimumRequiredBalance: .none, accountHolderAddressLine1: .none, accountHolderAddressLine2: .none, accountHolderStreetName: .none, town: .none, postCode: .none, countrySubDivision: .none, creditAccount: .none, debitAccount: .none, accountHolderCountry: .none, additions: .none, identifier: .none, unmaskableAttributes: [.bban], name: "Retirement Account 2", displayName: "Sarah William", externalTransferAllowed: true, crossCurrencyAllowed: true, productKindName: "Current Account", productTypeName: "Current Account", bankAlias: "unRetirement Account", sourceId: .none, visible: true, accountOpeningDate: .now, lastUpdateDate: .now, userPreferences: .init(alias: "Sarah William", visible: false, favorite: true, additions: nil), state: .init(externalStateId: "Active", state: "Active", additions: .none), parentId: .none, subArrangements: .none, financialInstitutionId: .none, lastSyncDate: .none, nextClosingDate: .none, reservedAmount: .none, remainingPeriodicTransfers: .none, overdueSince: .none, externalAccountStatus: .none, cardDetails: .none, interestDetails: .none),
                .init(bookedBalance: "0.4200000000", availableBalance: "0.4200000000", creditLimit: "0.00000", iban: .none, bban: "***************6946", currency: "USD", urgentTransferAllowed: .none, bic: "USXBUSHQXXX", bankBranchCode: "123123123", bankBranchCode2: .none, accountInterestRate: 3.00, valueDateBalance: .none, creditLimitUsage: 0.00000, creditLimitInterestRate: 2.00, creditLimitExpiryDate: .none, accruedInterest: .none, debitCardsItems: [], accountHolderNames: "Sarah Williams II", startDate: .none, minimumRequiredBalance: .none, accountHolderAddressLine1: .none, accountHolderAddressLine2: .none, accountHolderStreetName: .none, town: .none, postCode: .none, countrySubDivision: .none, creditAccount: .none, debitAccount: .none, accountHolderCountry: .none, additions: .none, identifier: .none, unmaskableAttributes: [.bban], name: "Retirement Account 3", displayName: "Sarah Williams II", externalTransferAllowed: true, crossCurrencyAllowed: true, productKindName: "Current Account", productTypeName: "Current Account", bankAlias: "Family Account", sourceId: .none, visible: true, accountOpeningDate: .now, lastUpdateDate: .now, userPreferences: .init(alias: "Sarah Williams II", visible: false, favorite: true, additions: nil), state: .init(externalStateId: "Active", state: "Active", additions: .none), parentId: .none, subArrangements: .none, financialInstitutionId: .none, lastSyncDate: .none, nextClosingDate: .none, reservedAmount: .none, remainingPeriodicTransfers: .none, overdueSince: .none, externalAccountStatus: .none, cardDetails: .none, interestDetails: .none),
                .init(bookedBalance: "0.4200000000", availableBalance: "0.4200000000", creditLimit: "0.00000", iban: .none, bban: "***************6947", currency: "USD", urgentTransferAllowed: .none, bic: "USXBUSHQXXX", bankBranchCode: "123123123", bankBranchCode2: .none, accountInterestRate: 3.00, valueDateBalance: .none, creditLimitUsage: 0.00000, creditLimitInterestRate: 2.00, creditLimitExpiryDate: .none, accruedInterest: .none, debitCardsItems: [], accountHolderNames: "Sarah Williams III", startDate: .none, minimumRequiredBalance: .none, accountHolderAddressLine1: .none, accountHolderAddressLine2: .none, accountHolderStreetName: .none, town: .none, postCode: .none, countrySubDivision: .none, creditAccount: .none, debitAccount: .none, accountHolderCountry: .none, additions: .none, identifier: .none, unmaskableAttributes: [.bban], name: "Family Account", displayName: "Sarah Williams III", externalTransferAllowed: true, crossCurrencyAllowed: true, productKindName: "Current Account", productTypeName: "Current Account", bankAlias: "Family Account", sourceId: .none, visible: true, accountOpeningDate: .now, lastUpdateDate: .now, userPreferences: .init(alias: "Sarah Williams III", visible: false, favorite: true, additions: nil), state: .init(externalStateId: "Active", state: "Active", additions: .none), parentId: .none, subArrangements: .none, financialInstitutionId: .none, lastSyncDate: .none, nextClosingDate: .none, reservedAmount: .none, remainingPeriodicTransfers: .none, overdueSince: .none, externalAccountStatus: .none, cardDetails: .none, interestDetails: .none)
            ], name: "Current Accounts", aggregatedBalance: .none, additions: .none), savingsAccounts: .none, termDeposits: .none, loans: .none, creditCards: .none, debitCards: .none, investmentAccounts: .none, additions: .none)))
        }
    }
}
// swiftlint:enable line_length
