//
// ProductKindsAPIRequestParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import ClientCommonGen2

public extension ProductKindsAPI {
    /// This class is used as a container class for request parameters for ProductKindsAPI.getProductKinds API call.
    struct GetProductKindsRequestParams: Equatable {
            /** Defines the translation natural language as specified in ISO 639-1, and territory two-letter form of ISO 3166. */
    public let contentLanguage: String?

    internal init(contentLanguage: String?) {
        self.contentLanguage = contentLanguage
    }
    /// Builder class for GetProductKindsRequestParams DTO.
    public final class Builder: Equatable {
        /** Defines the translation natural language as specified in ISO 639-1, and territory two-letter form of ISO 3166. */
        public private(set) var contentLanguage: String?

        public init() {
        }

        /// Setter method for contentLanguage property.
        public func set(contentLanguage: String?) -> Self {
            self.contentLanguage = contentLanguage
            return self
        }

        /// Builder initializer method for GetProductKindsRequestParams DTO.
        public func build() -> GetProductKindsRequestParams {
            return GetProductKindsRequestParams(contentLanguage: contentLanguage)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
        	return lhs.contentLanguage == rhs.contentLanguage
    	}
    }

public static func ==(lhs: Self, rhs: Self) -> Bool {
    return lhs.contentLanguage == rhs.contentLanguage
}
    }
}
