name: ios-golden-sample-app
options:
  bundleIdPrefix: com.backbase
  platform: iOS
  deploymentTarget:
    iOS: 15.0
targets:
  AccountsJourney:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: accounts-journey/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        MARKETING_VERSION: 0.0.1
        BUILD_LIBRARY_FOR_DISTRIBUTION: $(inherited)
    sources:
      - path: accounts-journey
        excludes:
          - Info.plist
        createIntermediateGroups: true
      - path: assets
        createIntermediateGroups: true
    scheme:
      testTargets:
        - AccountsJourneyUnitTests
      gatherCoverageData: true
    preBuildScripts:
      - name: SwiftLint
        script: |
            ${PODS_ROOT}/SwiftLint/swiftlint --config .swiftlint.yml            
  
  AppCommon:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: appCommon/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        MARKETING_VERSION: 0.0.1
        BUILD_LIBRARY_FOR_DISTRIBUTION: $(inherited)
    sources:
      - path: appCommon
        excludes:
          - Info.plist
        createIntermediateGroups: true
    dependencies:
      - target: AccountsJourney
        embed: true
    preBuildScripts:
      - name: SwiftLint
        script: |
            ${PODS_ROOT}/SwiftLint/swiftlint --config .swiftlint.yml

  GoldenSampleApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backbase.ebpsandbox.retailus
        MARKETING_VERSION: 0.0.1
    info:
      path: app/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleName: GoldenSampleApp
        UILaunchStoryboardName: LaunchScreen
    sources:
      - path: app
        excludes: Info.plist
        createIntermediateGroups: true
      - path: assets
        createIntermediateGroups: true
    dependencies:
      - target: AccountsJourney
        embed: true
      - target: AppCommon
        embed: true
    scheme:
      testTargets: []
      gatherCoverageData: false
    preBuildScripts:
      - name: SwiftLint
        script: |
            ${PODS_ROOT}/SwiftLint/swiftlint --config .swiftlint.yml
  GoldenSampleAllTests:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: Tests/all-tests/Info.plist
    codeSign: false
    settings:
      base:
        MARKETING_VERSION: 0.0.1
    dependencies:
      - target: AccountsJourney
        link: false
      - target: AppCommon
        link: false
    scheme:
      gatherCoverageData: true
      testTargets: 
        - name: AccountsJourneyUnitTests
          parallelizable: false
          randomExecutionOrder: true
        # - name: GoldenSampleUITests
        #   parallelizable: true
        #   randomExecutionOrder: false

  AccountsJourneyUnitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: Tests/accounts-journey/unit-tests/Info.plist
    codeSign: false
    dependencies:
      - target: AccountsJourney
        link: true
    sources:
      - path: Tests/accounts-journey/unit-tests
        excludes: Info.plist
        createIntermediateGroups: true

  # UITests1

  GoldenSampleUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: appUITests/Info.plist
    codeSign: false
    deploymentTarget:
      iOS: 15.0
    sources:
      - path: appUITests
        excludes: Info.plist
    dependencies:
      - target: GoldenSampleApp
        link: true
      - target: AccountsJourney
        link: true
    scheme:
      testTargets:
        - GoldenSampleUITests
      testPlans:
        - path: appUITests/TestPlans/L3.xctestplan
          defaultPlan: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backbase.goldensampleapp.UITests

    # Snapshot tests
    
  SnapshotTests:
    scheme:
      testTargets:
        - name: SnapshotTests
          randomExecutionOrder: true
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: Tests/SnapshotTests/Info.plist
    codeSign: false
    dependencies:
      - package: SnapshotTesting
      - target: GoldenSampleApp
        link: true
      - target: AccountsJourney
        link: true
    sources:
      - path: Tests/SnapshotTests
        excludes:
          - Info.plist
          - __Snapshots__
        createIntermediateGroups: true
      - path: Tests/SnapshotTests/__Snapshots__
        type: folder
        createIntermediateGroups: true
packages:
  SnapshotTesting:
    github: pointfreeco/swift-snapshot-testing
    from: 1.11.0
    
