name: ios-golden-sample-app
options:
  bundleIdPrefix: com.backbase
  deploymentTarget:
    iOS: 15.0
targets:
  AccountsJourney:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: accounts-journey/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        MARKETING_VERSION: 0.0.1
        BUILD_LIBRARY_FOR_DISTRIBUTION: $(inherited)
    sources:
      - path: accounts-journey
        excludes:
          - Info.plist
        createIntermediateGroups: true
      - path: assets
        createIntermediateGroups: true
    scheme:
      testTargets:
        - AccountsJourneyUnitTests
      gatherCoverageData: true
    preBuildScripts:
      - name: SwiftLint
        script: |
            ${PODS_ROOT}/SwiftLint/swiftlint --config .swiftlint.yml
  GoldenAccountsUseCase:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    info:
      path: accounts-use-case/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        MARKETING_VERSION: 0.0.1
        BUILD_LIBRARY_FOR_DISTRIBUTION: $(inherited)
    sources:
      - path: accounts-use-case
        excludes:
          - Info.plist
        createIntermediateGroups: true
    scheme:
      testTargets:
        - GoldenAccountsUseCaseUnitTests
      gatherCoverageData: true
    dependencies:
      - target: AccountsJourney
        link: true

  GoldenSampleApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backbase.ebpsandbox.retailus
        MARKETING_VERSION: 0.0.1
    info:
      path: app/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleName: GoldenSampleApp
        UILaunchStoryboardName: LaunchScreen
    sources:
      - path: app
        excludes: Info.plist
        createIntermediateGroups: true
    dependencies:
      - target: GoldenAccountsUseCase
        embed: true
      - target: AccountsJourney
        embed: true
  GoldenSampleAllTests:
    type: framework
    platform: iOS
    info:
      path: tests/all-tests/Info.plist
    codeSign: false
    settings:
      base:
        MARKETING_VERSION: 0.0.1
    dependencies:
      - target: AccountsJourney
        link: false
      - target: GoldenAccountsUseCase
        link: false
    scheme:
      gatherCoverageData: true
      testTargets: 
        - name: AccountsJourneyUnitTests
          parallelizable: false
          randomExecutionOrder: true
        - name: GoldenAccountsUseCaseUnitTests
          parallelizable: false
          randomExecutionOrder: true
        # - name: GoldenSampleUITests
        #   parallelizable: true
        #   randomExecutionOrder: false

  AccountsJourneyUnitTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: tests/accounts-journey/unit-tests/Info.plist
    codeSign: false
    dependencies:
      - target: AccountsJourney
        link: true
    sources:
      - path: tests/accounts-journey/unit-tests
        excludes: Info.plist
        createIntermediateGroups: true
  
  GoldenAccountsUseCaseUnitTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: tests/accounts-use-case/unit-tests/Info.plist
    codeSign: false
    dependencies:
      - target: AccountsJourney
        link: true
      - target: GoldenAccountsUseCase
        link: true
    sources:
      - path: tests/accounts-use-case/unit-tests
        excludes: Info.plist
        createIntermediateGroups: true

  # UITests1

  GoldenSampleUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: appUITests/Info.plist
    codeSign: false
    deploymentTarget:
      iOS: 15.0
    sources:
      - path: appUITests
        excludes: Info.plist
    dependencies:
      - target: GoldenSampleApp
        link: true
    scheme:
      testTargets:
        - GoldenSampleUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backbase.goldensampleapp.UITests