//
// AccountBalanceHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2


public struct AccountBalanceHistory: Codable, Equatable {
    public var items: [AccountBalanceHistoryForArrangement]
    public var additions: [String: String]?

    @available(*, deprecated, message: "This initializer is deprecated, use the initializer and the setters of AccountBalanceHistory.Builder class.")
    public init(items: [AccountBalanceHistoryForArrangement], additions: [String: String]? = nil) {
        self.items = items
        self.additions = additions
    }

    /// Builder class for AccountBalanceHistory DTO.
    public final class Builder: Equatable {
        public let items: [AccountBalanceHistoryForArrangement]
        public private(set) var additions: [String: String]?

        public init(items: [AccountBalanceHistoryForArrangement]) {
            self.items = items
        }

        /// Setter method for additions property.
        public func set(additions: [String: String]?) -> Self {
            self.additions = additions
            return self
        }

        /// Builder initializer method for AccountBalanceHistory DTO.
        public func build() -> AccountBalanceHistory {
            return AccountBalanceHistory(items: items, 
                    additions: additions)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
            return lhs.items == rhs.items &&
            lhs.additions == rhs.additions
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)
        try container.encode(items, forKey: "items")
        try container.encodeIfPresent(additions, forKey: "additions")
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        items = try container.decode([AccountBalanceHistoryForArrangement].self, forKey: "items")
        additions = try container.decodeIfPresent([String: String].self, forKey: "additions")
    }

    public static func ==(lhs: AccountBalanceHistory, rhs: AccountBalanceHistory) -> Bool {
        return lhs.items == rhs.items &&
        lhs.additions == rhs.additions
    }


}
