//
// ApiError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2


public struct ApiError: Codable, Equatable {
    public var message: String

    @available(*, deprecated, message: "This initializer is deprecated, use the initializer and the setters of ApiError.Builder class.")
    public init(message: String) {
        self.message = message
    }

    /// Builder class for ApiError DTO.
    public final class Builder: Equatable {
        public let message: String

        public init(message: String) {
            self.message = message
        }


        /// Builder initializer method for ApiError DTO.
        public func build() -> ApiError {
            return ApiError(message: message)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
            return lhs.message == rhs.message
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)
        try container.encode(message, forKey: "message")
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        message = try container.decode(String.self, forKey: "message")
    }

    public static func ==(lhs: ApiError, rhs: ApiError) -> Bool {
        return lhs.message == rhs.message
    }


}
