//
// BadRequestError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2


public struct BadRequestError: Codable, Equatable {
    /** Detailed error information */
    public var errors: [ErrorItem]
    public var message: String

    @available(*, deprecated, message: "This initializer is deprecated, use the initializer and the setters of BadRequestError.Builder class.")
    public init(errors: [ErrorItem], message: String) {
        self.errors = errors
        self.message = message
    }

    /// Builder class for BadRequestError DTO.
    public final class Builder: Equatable {
        /** Detailed error information */
        public let errors: [ErrorItem]
        public let message: String

        public init(errors: [ErrorItem], message: String) {
            self.errors = errors
            self.message = message
        }


        /// Builder initializer method for BadRequestError DTO.
        public func build() -> BadRequestError {
            return BadRequestError(errors: errors, 
                    message: message)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
            return lhs.errors == rhs.errors &&
            lhs.message == rhs.message
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)
        try container.encode(errors, forKey: "errors")
        try container.encode(message, forKey: "message")
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        errors = try container.decode([ErrorItem].self, forKey: "errors")
        message = try container.decode(String.self, forKey: "message")
    }

    public static func ==(lhs: BadRequestError, rhs: BadRequestError) -> Bool {
        return lhs.errors == rhs.errors &&
        lhs.message == rhs.message
    }


}
