//
// CustomProductKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2


public struct CustomProductKind: Codable, Equatable {
    /** The label/name that is used for the respective product kind */
    public var name: String?
    public var id: Int?
    public var products: [GeneralAccount]
    public var aggregatedBalance: SummaryAggregatedBalance?
    public var additions: [String: String]?

    @available(*, deprecated, message: "This initializer is deprecated, use the initializer and the setters of CustomProductKind.Builder class.")
    public init(name: String? = nil, id: Int? = nil, products: [GeneralAccount], aggregatedBalance: SummaryAggregatedBalance? = nil, additions: [String: String]? = nil) {
        self.name = name
        self.id = id
        self.products = products
        self.aggregatedBalance = aggregatedBalance
        self.additions = additions
    }

    /// Builder class for CustomProductKind DTO.
    public final class Builder: Equatable {
        /** The label/name that is used for the respective product kind */
        public private(set) var name: String?
        public private(set) var id: Int?
        public let products: [GeneralAccount]
        public private(set) var aggregatedBalance: SummaryAggregatedBalance?
        public private(set) var additions: [String: String]?

        public init(products: [GeneralAccount]) {
            self.products = products
        }

        /// Setter method for name property.
        public func set(name: String?) -> Self {
            self.name = name
            return self
        }
        /// Setter method for id property.
        public func set(id: Int?) -> Self {
            self.id = id
            return self
        }
        /// Setter method for aggregatedBalance property.
        public func set(aggregatedBalance: SummaryAggregatedBalance?) -> Self {
            self.aggregatedBalance = aggregatedBalance
            return self
        }
        /// Setter method for additions property.
        public func set(additions: [String: String]?) -> Self {
            self.additions = additions
            return self
        }

        /// Builder initializer method for CustomProductKind DTO.
        public func build() -> CustomProductKind {
            return CustomProductKind(name: name, 
                    id: id, 
                    products: products, 
                    aggregatedBalance: aggregatedBalance, 
                    additions: additions)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
            return lhs.name == rhs.name &&
            lhs.id == rhs.id &&
            lhs.products == rhs.products &&
            lhs.aggregatedBalance == rhs.aggregatedBalance &&
            lhs.additions == rhs.additions
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encode(products, forKey: "products")
        try container.encodeIfPresent(aggregatedBalance, forKey: "aggregatedBalance")
        try container.encodeIfPresent(additions, forKey: "additions")
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        name = try container.decodeIfPresent(String.self, forKey: "name")
        id = try container.decodeIfPresent(Int.self, forKey: "id")
        products = try container.decode([GeneralAccount].self, forKey: "products")
        aggregatedBalance = try container.decodeIfPresent(SummaryAggregatedBalance.self, forKey: "aggregatedBalance")
        additions = try container.decodeIfPresent([String: String].self, forKey: "additions")
    }

    public static func ==(lhs: CustomProductKind, rhs: CustomProductKind) -> Bool {
        return lhs.name == rhs.name &&
        lhs.id == rhs.id &&
        lhs.products == rhs.products &&
        lhs.aggregatedBalance == rhs.aggregatedBalance &&
        lhs.additions == rhs.additions
    }


}
