//
// MaskableAttribute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2

/** The name of the supported maskable attribute. */
public enum MaskableAttribute: String, Codable, CaseIterable {
    case iban = "IBAN"
    case bban = "BBAN"
    case number = "number"
}
