//
// OrderByField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2

/** The property name used for ordering. */
public enum OrderByField: String, Codable, CaseIterable {
    case name = "name"
    case bankalias = "bankAlias"
    case bookedbalance = "bookedBalance"
    case availablebalance = "availableBalance"
    case creditlimit = "creditLimit"
    case displayname = "displayName"
    case iban = "IBAN"
    case bban = "BBAN"
    case bic = "BIC"
    case currency = "currency"
    case externaltransferallowed = "externalTransferAllowed"
    case urgenttransferallowed = "urgentTransferAllowed"
    case accruedinterest = "accruedInterest"
    case principalamount = "principalAmount"
    case currentinvestmentvalue = "currentInvestmentValue"
    case productnumber = "productNumber"
    case accountopeningdate = "accountOpeningDate"
    case accountinterestrate = "accountInterestRate"
    case valuedatebalance = "valueDateBalance"
    case creditlimitusage = "creditLimitUsage"
    case creditlimitinterestrate = "creditLimitInterestRate"
    case creditlimitexpirydate = "creditLimitExpiryDate"
    case startdate = "startDate"
    case termunit = "termUnit"
    case termnumber = "termNumber"
    case maturitydate = "maturityDate"
    case maturityamount = "maturityAmount"
    case autorenewalindicator = "autoRenewalIndicator"
    case interestpaymentfrequencyunit = "interestPaymentFrequencyUnit"
    case interestpaymentfrequencynumber = "interestPaymentFrequencyNumber"
    case interestsettlementaccount = "interestSettlementAccount"
    case outstandingprincipalamount = "outstandingPrincipalAmount"
    case monthlyinstalmentamount = "monthlyInstalmentAmount"
    case amountinarrear = "amountInArrear"
    case minimumrequiredbalance = "minimumRequiredBalance"
    case creditcardaccountnumber = "creditCardAccountNumber"
    case validthru = "validThru"
    case applicableinterestrate = "applicableInterestRate"
    case remainingcredit = "remainingCredit"
    case outstandingpayment = "outstandingPayment"
    case minimumpayment = "minimumPayment"
    case minimumpaymentduedate = "minimumPaymentDueDate"
    case totalinvestmentvalue = "totalInvestmentValue"
    case accountholderaddressline1 = "accountHolderAddressLine1"
    case accountholderaddressline2 = "accountHolderAddressLine2"
    case accountholderstreetname = "accountHolderStreetName"
    case postcode = "postCode"
    case town = "town"
    case countrysubdivision = "countrySubDivision"
    case accountholdercountry = "accountHolderCountry"
    case creditaccount = "creditAccount"
    case debitaccount = "debitAccount"
    case productkindname = "productKindName"
    case producttypename = "productTypeName"
    case sourceid = "sourceId"
}
