//
// ProductSummaryFilterResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2


public struct ProductSummaryFilterResult: Codable, Equatable {
    public var totalCount: Int
    public var items: [ProductSummaryItem]
    public var additions: [String: String]?

    @available(*, deprecated, message: "This initializer is deprecated, use the initializer and the setters of ProductSummaryFilterResult.Builder class.")
    public init(totalCount: Int, items: [ProductSummaryItem], additions: [String: String]? = nil) {
        self.totalCount = totalCount
        self.items = items
        self.additions = additions
    }

    /// Builder class for ProductSummaryFilterResult DTO.
    public final class Builder: Equatable {
        public let totalCount: Int
        public let items: [ProductSummaryItem]
        public private(set) var additions: [String: String]?

        public init(totalCount: Int, items: [ProductSummaryItem]) {
            self.totalCount = totalCount
            self.items = items
        }

        /// Setter method for additions property.
        public func set(additions: [String: String]?) -> Self {
            self.additions = additions
            return self
        }

        /// Builder initializer method for ProductSummaryFilterResult DTO.
        public func build() -> ProductSummaryFilterResult {
            return ProductSummaryFilterResult(totalCount: totalCount, 
                    items: items, 
                    additions: additions)
        }

        public static func ==(lhs: Builder, rhs: Builder) -> Bool {
            return lhs.totalCount == rhs.totalCount &&
            lhs.items == rhs.items &&
            lhs.additions == rhs.additions
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)
        try container.encode(totalCount, forKey: "totalCount")
        try container.encode(items, forKey: "items")
        try container.encodeIfPresent(additions, forKey: "additions")
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)
        totalCount = try container.decode(Int.self, forKey: "totalCount")
        items = try container.decode([ProductSummaryItem].self, forKey: "items")
        additions = try container.decodeIfPresent([String: String].self, forKey: "additions")
    }

    public static func ==(lhs: ProductSummaryFilterResult, rhs: ProductSummaryFilterResult) -> Bool {
        return lhs.totalCount == rhs.totalCount &&
        lhs.items == rhs.items &&
        lhs.additions == rhs.additions
    }


}
