//
// SortDirection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2

/** Whether to sort results in ascendent or descendent order. */
public enum SortDirection: String, Codable, CaseIterable {
    case asc = "ASC"
    case desc = "DESC"
}
