//
// TimeUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import ClientCommonGen2

/** The period of time for the product arranged between Bank and customer */
public enum TimeUnit: String, Codable, CaseIterable {
    case d = "D"
    case w = "W"
    case m = "M"
    case y = "Y"
}
