= Mutation Testing

Mutation testing is a technique used to evaluate the quality of your test suite by introducing small changes (mutations) to your code and checking if your tests can detect these changes.
The goal is to ensure that your tests are robust and can catch potential bugs.

In this document we will look into how we use link:https://github.com/muter-mutation-testing/muter[muter] to perform mutation testing on our iOS project.

== Installation

Normally you would install muter using homebrew. You can do this by running the following command in your terminal:

```bash
brew install muter-mutation-testing/formulae/muter
```

However the latest release gives a segmentation fault (see link:https://github.com/muter-mutation-testing/muter/issues/228[issue]) therefore I had to compile the package manually.

== Setup

To set up muter for your project, navigate to the root directory of your iOS project and run:

```bash
muter init
```

Then create a configuration file named `muter.yml` in the root directory of your project with the following content:

```yam'
arguments:
  - exec
  - fastlane
  - test
executable: bundle
exclude: []
excludeCalls: []
```

Since all iOS projects use link:https://fastlane.tools:[fastlane] to run tests, the config file can be the same across all journey repositories.

== To run mutation tests

```bash
muter run
```

== Observations

Running `muter` against all tests in the Golden Sample App would take about 104 hours.
To reduce the time, I limited the scope to certain files using the `--files-to-mutate` flag.

```bash
muter --files-to-mutate accounts-journey/presentation/ui/account_detail/AccountDetailsViewController.swift
```

This single files (with 27 mutants) took about 22 minutes, mostly because the tests are slow, and it produced the following report:

```bash
                   ▃▃▃▃▃▃▃
                   ▜██████▙
                  ▟█▛███▜██▙
                 ▃▃▃  ▟█████
                 ▜██▙    ███
                  ▝▜██▙ ▟███
                    ▝▜██████
                      ▝▜████
                  ▟██▙ ▟████▟█▙
                ▟██▙██▙█████▟██▙▄̵̵
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
   ▟█▙    ▟█▙ ▟▙    ▟▙ ████████ ▟█████▙ ▟████▙
   ███▙  ▟███ ██    ██    ██    ██      ██   ██
   ██ ▜██▛ ██ ██    ██    ██    ██ ████ █████▛
   ██      ██ ██    ██    ██    ██      ██  ▜█▙
   ▜▛      ▜▛  ▜████▛     ▜▛    ▜█████▛ ▜▛    ▜█

Automated mutation testing for Swift 🕳️

You are running version 16

Want help? Have suggestions? Want to get involved?
 ↳ https://github.com/muter-mutation-testing/muter/issues
+--------------------------------------------------------+

🔎 Checking for new versions...
✅ You are already using the latest of Muter
✂️ Copying your project to a temporary directory for testing...
✅ Finished copying your project to a temporary directory for mutation testing.
You can find your copied project here:

/Users/dunya@backbase.com/Projects/golden-sample-app-ios_mutated

This directory will also serve as a backup for any XCTest logs that are generated by running your test suite.
+-----------------+
🔎 Discovering Swift files which Muter will analyze...
✅ In total, Muter discovered 1 Swift files

AccountDetailsViewController.swift
+-----------------+
🔎 Analyzing source files to find mutants which can be inserted into your project...
✅ In total, Muter discovered 27 mutants in 1 files

AccountDetailsViewController.swift (27 mutants)
+-----------------+
🚀 Mutation testing will now begin
⚙️ Running your test suite to determine a baseline for mutation testing...
📊 Determined baseline for mutation testing.
🧟 Muter is now going to apply each mutant one at a time and run your test suite for each mutant.
📃 After this step, Muter will generate a report detailing the efficacy of your test suite.
☕️ This step may take a while.
Inserting mutant 27 of 27
Percentage complete:  100% [--------------------------------------------------] ETC: 0 minute
🏁 Muter finished running!
📝 Muter's report

--------------------------
Applied Mutation Operators
--------------------------

These are all of the ways that Muter introduced changes into your code.

In total, Muter introduced 27 mutants in 1 files.

File                                     Applied Mutation Operator       Mutation Test Result
----                                     -------------------------       --------------------
AccountDetailsViewController.swift:267   RelationalOperatorReplacement   mutant survived
AccountDetailsViewController.swift:120   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:126   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:141   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:151   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:152   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:154   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:155   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:164   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:165   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:166   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:168   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:169   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:170   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:244   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:249   RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:61    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:62    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:63    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:67    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:70    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:72    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:73    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:77    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:78    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:79    RemoveSideEffects               mutant survived
AccountDetailsViewController.swift:97    RemoveSideEffects               mutant survived


--------------------
Mutation Test Scores
--------------------

Muter took 00:23:04.267 to run.

These are the mutation scores for your test suite, as well as the files that had mutants introduced into them.

Mutation scores ignore build errors.

Of the 27 mutants introduced into your code, your test suite killed 0.
Mutation Score of Test Suite: 0%
Muter could not gather coverage data from your project

File                                 # of Introduced Mutants   Mutation Score
----                                 -----------------------   --------------
AccountDetailsViewController.swift   27                        0
```
