name: Build and Test GoldenSampeApp
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-tests:
    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Gems 
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate the project file
        run: bundle exec fastlane setup
      - name: Run tests
        run: bundle exec fastlane test
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" ./DerivedData/Build/Products/Debug/Curtz.framework/Curtz -instr-profile DerivedData/Build/ProfileData/*/Coverage.profdata > coverage_report.lcov